image: maven:3-jdk-11

before_script:
  - apt-get install ant

stages:
  - package

package:
  stage: package

  variables:
    GIT_STRATEGY: clone
  script:
    - cd nusano
    - bash build.sh
    - cd ..
  artifacts:
    name: "phoebus_$CI_COMMIT_TAG"
    paths:
     - phoebus-product/target/phoebus-4.6.0-linux.zip
     - nusano/phoebus
     - nusano/phoebus.desktop
     - nusano/logo.png
     - nusano/deploy.sh
