image: maven:3-jdk-11

before_script:
  - apt-get update -y
  - apt-get install ant -y

stages:
  - package

package:
  stage: package

  variables:
    GIT_STRATEGY: clone
  script:
    - cd nusano
    - bash build.sh
    - cd ..
    - cp phoebus-product/target/phoebus-4.6.0-linux.zip .
    - cp nusano/phoebus .
    - cp nusano/phoebus.desktop .
    - cp nusano/logo.png .
    - cp nusano/deploy.sh .
  artifacts:
    name: "phoebus-$CI_COMMIT_TAG"
    paths:
     - phoebus-4.6.0-linux.zip
     - phoebus
     - phoebus.desktop
     - logo.png
     - deploy.sh
